"""tryout add name

Revision ID: 1a8e1033b0c1
Revises: 86a514cfd1fe
Create Date: 2025-03-21 21:02:04.906735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a8e1033b0c1"
down_revision: Union[str, None] = "86a514cfd1fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tryouts", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tryouts", "name")
    # ### end Alembic commands ###
