"""add registration start time and end time and  isApplied

Revision ID: 86a514cfd1fe
Revises: 610ed047b701
Create Date: 2025-03-21 20:54:48.913029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86a514cfd1fe'
down_revision: Union[str, None] = '610ed047b701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tryouts', sa.Column('registration_start_time', sa.DateTime(), nullable=False))
    op.add_column('tryouts', sa.Column('registration_end_time', sa.DateTime(), nullable=False))
    op.drop_column('tryouts', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tryouts', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('tryouts', 'registration_end_time')
    op.drop_column('tryouts', 'registration_start_time')
    # ### end Alembic commands ###
