"""add end_time for slot

Revision ID: efbe3a73f1af
Revises: 1551c17641e7
Create Date: 2025-03-23 13:35:43.268732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbe3a73f1af'
down_revision: Union[str, None] = '1551c17641e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tryouts', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tryouts', 'end_time')
    # ### end Alembic commands ###
